const url = {
  createServiceUrl: '/api/v1/business/service/create/',
  updateServiceUrl: '/api/v1/business/service/update/',
  deleteServiceUrl: '/api/v1/business/service/delete/',
  getServiceListUrl: '/api/v1/business/service/list/',
  getServiceUrl: '/api/v1/business/service/',
  createServiceDepartmentUrl: '/api/v1/business/service/department/create/',
  deleteServiceDepartmentUrl: '/api/v1/business/service/department/delete/',
  getServiceDepartmentListUrl: '/api/v1/business/service/department/list/',
  createServiceUserUrl: '/api/v1/business/service/user/create/',
  updateServiceUserUrl: '/api/v1/business/service/user/update/',
  deleteServiceUserUrl: '/api/v1/business/service/user/delete/',
  getServiceUserListUrl: '/api/v1/business/service/user/list/',
  createServiceEnvironmentUrl: '/api/v1/business/service/environment/create/',
  deleteServiceEnvironmentUrl: '/api/v1/business/service/environment/delete/',
  getServiceEnvironmentListUrl: '/api/v1/business/service/environment/list/',
  createServiceAssetUrl: '/api/v1/business/service/asset/create/',
  deleteServiceAssetUrl: '/api/v1/business/service/asset/delete/',
  getServiceAssetListUrl: '/api/v1/business/service/asset/list/',
  createServiceEcsUrl: '/api/v1/business/service/ecs/create/',
  deleteServiceEcsUrl: '/api/v1/business/service/ecs/delete/',
  getServiceEcsListUrl: '/api/v1/business/service/ecs/list/',
  createServiceServerGroupUrl: '/api/v1/business/service/server/group/create/',
  deleteServiceServerGroupUrl: '/api/v1/business/service/server/group/delete/',
  getServiceServerGroupListUrl: '/api/v1/business/service/server/group/list/',
  createServiceDatabaseUrl: '/api/v1/business/service/database/create/',
  deleteServiceDatabaseUrl: '/api/v1/business/service/database/delete/',
  getServiceDatabaseListUrl: '/api/v1/business/service/database/list/'
}

export default url
